# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Sim_Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(165, 235, 69, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(241, 9, 16, 276))
        self.widget.setObjectName("widget")
        self.dial_T = QtWidgets.QDial(self.centralwidget)
        self.dial_T.setGeometry(QtCore.QRect(10, 104, 50, 50))
        self.dial_T.setAutoFillBackground(False)
        self.dial_T.setWrapping(False)
        self.dial_T.setNotchTarget(5.0)
        self.dial_T.setNotchesVisible(True)
        self.dial_T.setObjectName("dial_T")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(66, 235, 34, 16))
        self.label.setObjectName("label")
        self.lineEdit_V = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_V.setGeometry(QtCore.QRect(66, 44, 93, 20))
        self.lineEdit_V.setObjectName("lineEdit_V")
        self.label_V = QtWidgets.QLabel(self.centralwidget)
        self.label_V.setGeometry(QtCore.QRect(70, 20, 40, 16))
        self.label_V.setObjectName("label_V")
        self.lineEdit_N = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_N.setGeometry(QtCore.QRect(66, 194, 93, 20))
        self.lineEdit_N.setObjectName("lineEdit_N")
        self.label_T = QtWidgets.QLabel(self.centralwidget)
        self.label_T.setGeometry(QtCore.QRect(70, 90, 56, 16))
        self.label_T.setObjectName("label_T")
        self.label_N = QtWidgets.QLabel(self.centralwidget)
        self.label_N.setGeometry(QtCore.QRect(70, 170, 93, 16))
        self.label_N.setObjectName("label_N")
        self.lineEdit_T = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_T.setGeometry(QtCore.QRect(66, 119, 93, 20))
        self.lineEdit_T.setObjectName("lineEdit_T")
        self.comboBox_T = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_T.setGeometry(QtCore.QRect(165, 119, 69, 20))
        self.comboBox_T.setObjectName("comboBox_T")
        self.comboBox_T.addItem("")
        self.comboBox_T.addItem("")
        self.dial_N = QtWidgets.QDial(self.centralwidget)
        self.dial_N.setGeometry(QtCore.QRect(10, 179, 50, 50))
        self.dial_N.setAutoFillBackground(False)
        self.dial_N.setWrapping(False)
        self.dial_N.setNotchTarget(5.0)
        self.dial_N.setNotchesVisible(True)
        self.dial_N.setObjectName("dial_N")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 270, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.dial_V = QtWidgets.QDial(self.centralwidget)
        self.dial_V.setGeometry(QtCore.QRect(10, 29, 50, 50))
        self.dial_V.setAutoFillBackground(False)
        self.dial_V.setWrapping(False)
        self.dial_V.setNotchTarget(5.0)
        self.dial_V.setNotchesVisible(True)
        self.dial_V.setObjectName("dial_V")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 260, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSpeichern = QtWidgets.QAction(MainWindow)
        self.actionSpeichern.setObjectName("actionSpeichern")
        self.action_fnnen = QtWidgets.QAction(MainWindow)
        self.action_fnnen.setObjectName("action_fnnen")
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionSpeichern)
        self.menuDatei.addAction(self.action_fnnen)
        self.menubar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "hPa"))
        self.comboBox.setItemText(1, _translate("MainWindow", "kPa"))
        self.comboBox.setItemText(2, _translate("MainWindow", "bar"))
        self.label.setText(_translate("MainWindow", "Druck: "))
        self.label_V.setText(_translate("MainWindow", "Volumen"))
        self.label_T.setText(_translate("MainWindow", "Temperatur"))
        self.label_N.setText(_translate("MainWindow", "Anzahl der Teilchen"))
        self.comboBox_T.setItemText(0, _translate("MainWindow", "K"))
        self.comboBox_T.setItemText(1, _translate("MainWindow", "°C"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.actionSpeichern.setText(_translate("MainWindow", "Speichern"))
        self.action_fnnen.setText(_translate("MainWindow", "Öfnnen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

